spring:
  application:
    name: l09_spring_login
  profiles:
    include: deploy
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
#    include: dev
server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12  # src/main/resources에 복사한 경우
    key-store-type: PKCS12
    key-store-password: ${ssl.pw}
    key-alias: myssl
cloud:
  aws:
    credentials:
      access-key: ${aws.access.key}
      secret-key: ${aws.secret.key}
    region:
      static: ${aws.s3.region}
    s3:
      bucket: ${aws.s3.bucket}
