spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 966155629484-f6brj2njj75b8emskamh6mdq8upe0faq.apps.googleusercontent.com
            client-secret: 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
            #구글에서 로그인 성공시 정보를 전달하는 url
            scope: profile, email
