spring:
  application:
    name: l09_spring_login
  datasource:
    url: jdbc:mysql://localhost:3306/login_study
    username: root
    password: mysqlmysql
server:
  port: 9999
logging:
  level:
    org:
      springframework:
        security: DEBUG